// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservationSystemBackend.Data;

#nullable disable

namespace ReservationSystemBackend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607213642_FixingEntitiesNavigationErrors")]
    partial class FixingEntitiesNavigationErrors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReservationSystemBackend.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hilton"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Marriott"
                        });
                });

            modelBuilder.Entity("ReservationSystemBackend.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InvestorId")
                        .HasColumnType("int");

                    b.Property<int>("PresenterId")
                        .HasColumnType("int");

                    b.Property<int>("RoomSlotId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomSlotId1")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvestorId");

                    b.HasIndex("PresenterId");

                    b.HasIndex("RoomSlotId")
                        .IsUnique();

                    b.HasIndex("RoomSlotId1")
                        .IsUnique()
                        .HasFilter("[RoomSlotId1] IS NOT NULL");

                    b.HasIndex("TopicId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ReservationSystemBackend.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HotelId = 1,
                            Name = "Conference Room 1"
                        },
                        new
                        {
                            Id = 2,
                            HotelId = 1,
                            Name = "Conference Room 2"
                        },
                        new
                        {
                            Id = 3,
                            HotelId = 2,
                            Name = "Conference Room A"
                        });
                });

            modelBuilder.Entity("ReservationSystemBackend.Entities.RoomSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoomId = 1,
                            StartTime = new DateTime(2026, 6, 1, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            RoomId = 1,
                            StartTime = new DateTime(2026, 6, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            RoomId = 1,
                            StartTime = new DateTime(2026, 6, 1, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            RoomId = 2,
                            StartTime = new DateTime(2026, 6, 1, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            RoomId = 2,
                            StartTime = new DateTime(2026, 6, 1, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            RoomId = 3,
                            StartTime = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            RoomId = 3,
                            StartTime = new DateTime(2026, 6, 1, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            RoomId = 3,
                            StartTime = new DateTime(2026, 6, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ReservationSystemBackend.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Restaurants"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Real Estate"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Retail"
                        });
                });

            modelBuilder.Entity("ReservationSystemBackend.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mobile = "01000000000",
                            Name = "Admin",
                            UserType = 1
                        },
                        new
                        {
                            Id = 2,
                            Mobile = "01011111111",
                            Name = "CIB",
                            UserType = 2
                        },
                        new
                        {
                            Id = 3,
                            Mobile = "01022222222",
                            Name = "EFG Hermes",
                            UserType = 2
                        },
                        new
                        {
                            Id = 4,
                            Mobile = "01033333333",
                            Name = "Oltob",
                            UserType = 3
                        },
                        new
                        {
                            Id = 5,
                            Mobile = "01044444444",
                            Name = "Tech Solutions",
                            UserType = 3
                        });
                });

            modelBuilder.Entity("ReservationSystemBackend.Entities.UserTopicAvaliability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AvaliabilityFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AvaliabilityTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTopicAvaliabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvaliabilityFrom = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            AvaliabilityTo = new DateTime(2026, 6, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            AvaliabilityFrom = new DateTime(2026, 6, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            AvaliabilityTo = new DateTime(2026, 6, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            AvaliabilityFrom = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            AvaliabilityTo = new DateTime(2026, 6, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            AvaliabilityFrom = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            AvaliabilityTo = new DateTime(2026, 6, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            AvaliabilityFrom = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            AvaliabilityTo = new DateTime(2026, 6, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 2,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("ReservationSystemBackend.Entities.Reservation", b =>
                {
                    b.HasOne("ReservationSystemBackend.Entities.User", "Investor")
                        .WithMany()
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationSystemBackend.Entities.User", "Presenter")
                        .WithMany()
                        .HasForeignKey("PresenterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReservationSystemBackend.Entities.RoomSlot", "RoomSlot")
                        .WithOne()
                        .HasForeignKey("ReservationSystemBackend.Entities.Reservation", "RoomSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationSystemBackend.Entities.RoomSlot", null)
                        .WithOne("Reservation")
                        .HasForeignKey("ReservationSystemBackend.Entities.Reservation", "RoomSlotId1");

                    b.HasOne("ReservationSystemBackend.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");

                    b.Navigation("Presenter");

                    b.Navigation("RoomSlot");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("ReservationSystemBackend.Entities.Room", b =>
                {
                    b.HasOne("ReservationSystemBackend.Entities.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("ReservationSystemBackend.Entities.RoomSlot", b =>
                {
                    b.HasOne("ReservationSystemBackend.Entities.Room", "Room")
                        .WithMany("RoomSlots")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ReservationSystemBackend.Entities.UserTopicAvaliability", b =>
                {
                    b.HasOne("ReservationSystemBackend.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationSystemBackend.Entities.User", "User")
                        .WithMany("UserTopicAvaliabilities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReservationSystemBackend.Entities.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("ReservationSystemBackend.Entities.Room", b =>
                {
                    b.Navigation("RoomSlots");
                });

            modelBuilder.Entity("ReservationSystemBackend.Entities.RoomSlot", b =>
                {
                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("ReservationSystemBackend.Entities.User", b =>
                {
                    b.Navigation("UserTopicAvaliabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
